INSERT INTO Course (course_id, title, lecturer_id) VALUES (1, 'Basics of Stand', 2026001);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (2, 'Fundamentals of Understand', 2026002);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (3, 'Principles of Usually', 2026003);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (4, 'Advanced Professional', 2026004);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (5, 'Basics of Eye', 2026005);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (6, 'Introduction to Figure', 2026006);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (7, 'Advanced Serious', 2026007);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (8, 'Advanced Son', 2026008);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (9, 'Principles of Give', 2026009);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (10, 'Advanced Response', 2026010);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (11, 'Principles of Traditional', 2026011);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (12, 'Principles of Into', 2026012);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (13, 'Fundamentals of Color', 2026013);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (14, 'Advanced Own', 2026014);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (15, 'Introduction to Central', 2026015);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (16, 'Fundamentals of Despite', 2026016);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (17, 'Introduction to Huge', 2026017);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (18, 'Principles of Spend', 2026018);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (19, 'Principles of In', 2026019);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (20, 'Introduction to Home', 2026020);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (21, 'Basics of Continue', 2026021);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (22, 'Fundamentals of That', 2026022);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (23, 'Advanced Ask', 2026023);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (24, 'Advanced Field', 2026024);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (25, 'Fundamentals of Military', 2026025);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (26, 'Advanced Similar', 2026026);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (27, 'Principles of Of', 2026027);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (28, 'Principles of Thought', 2026028);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (29, 'Basics of Bed', 2026029);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (30, 'Introduction to Consumer', 2026030);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (31, 'Introduction to Course', 2026031);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (32, 'Basics of Baby', 2026032);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (33, 'Fundamentals of Often', 2026033);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (34, 'Fundamentals of Art', 2026034);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (35, 'Advanced Spend', 2026035);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (36, 'Basics of Force', 2026036);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (37, 'Fundamentals of System', 2026037);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (38, 'Advanced Forward', 2026038);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (39, 'Basics of Mr', 2026039);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (40, 'Fundamentals of Or', 2026040);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (41, 'Advanced Piece', 2026041);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (42, 'Fundamentals of Guess', 2026042);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (43, 'Introduction to Establish', 2026043);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (44, 'Basics of Notice', 2026044);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (45, 'Introduction to Expect', 2026045);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (46, 'Principles of Old', 2026046);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (47, 'Principles of Visit', 2026047);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (48, 'Basics of Simply', 2026048);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (49, 'Basics of Cultural', 2026049);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (50, 'Principles of Everything', 2026050);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (51, 'Basics of Civil', 2026009);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (52, 'Basics of Skill', 2026003);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (53, 'Basics of Trouble', 2026026);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (54, 'Basics of Charge', 2026013);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (55, 'Advanced Amount', 2026021);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (56, 'Fundamentals of Represent', 2026003);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (57, 'Fundamentals of Next', 2026048);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (58, 'Basics of Claim', 2026040);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (59, 'Advanced Single', 2026029);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (60, 'Introduction to Cover', 2026047);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (61, 'Advanced Election', 2026016);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (62, 'Principles of Try', 2026048);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (63, 'Principles of Left', 2026002);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (64, 'Introduction to Drive', 2026017);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (65, 'Basics of Character', 2026034);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (66, 'Principles of Listen', 2026036);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (67, 'Principles of Statement', 2026018);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (68, 'Fundamentals of Total', 2026010);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (69, 'Advanced Authority', 2026028);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (70, 'Principles of Glass', 2026017);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (71, 'Fundamentals of Capital', 2026042);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (72, 'Basics of Result', 2026020);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (73, 'Basics of This', 2026044);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (74, 'Advanced Benefit', 2026014);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (75, 'Principles of Suddenly', 2026034);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (76, 'Basics of Professor', 2026002);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (77, 'Principles of Must', 2026041);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (78, 'Basics of Thought', 2026007);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (79, 'Principles of Stay', 2026005);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (80, 'Basics of Large', 2026029);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (81, 'Basics of Decade', 2026033);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (82, 'Advanced Pick', 2026003);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (83, 'Basics of Store', 2026020);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (84, 'Fundamentals of Popular', 2026027);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (85, 'Principles of Government', 2026038);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (86, 'Basics of Account', 2026019);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (87, 'Introduction to Affect', 2026016);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (88, 'Advanced Improve', 2026034);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (89, 'Advanced Mind', 2026025);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (90, 'Fundamentals of Dog', 2026002);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (91, 'Fundamentals of Commercial', 2026016);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (92, 'Basics of By', 2026038);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (93, 'Principles of Audience', 2026002);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (94, 'Principles of Use', 2026041);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (95, 'Fundamentals of Season', 2026027);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (96, 'Fundamentals of World', 2026017);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (97, 'Fundamentals of Hotel', 2026043);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (98, 'Basics of Form', 2026037);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (99, 'Introduction to Way', 2026009);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (100, 'Principles of Beyond', 2026022);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (101, 'Principles of Continue', 2026050);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (102, 'Principles of Collection', 2026043);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (103, 'Advanced Raise', 2026012);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (104, 'Introduction to Each', 2026036);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (105, 'Basics of Major', 2026021);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (106, 'Basics of Serve', 2026012);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (107, 'Advanced Feel', 2026049);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (108, 'Basics of Relate', 2026029);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (109, 'Basics of Particular', 2026040);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (110, 'Fundamentals of General', 2026044);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (111, 'Introduction to Wait', 2026021);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (112, 'Fundamentals of Hot', 2026027);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (113, 'Advanced Peace', 2026044);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (114, 'Basics of Particular', 2026023);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (115, 'Advanced Ground', 2026017);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (116, 'Basics of Prepare', 2026011);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (117, 'Basics of Those', 2026043);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (118, 'Advanced Figure', 2026035);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (119, 'Basics of Indeed', 2026036);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (120, 'Basics of Grow', 2026045);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (121, 'Basics of Write', 2026025);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (122, 'Fundamentals of Case', 2026040);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (123, 'Principles of Season', 2026018);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (124, 'Advanced Whatever', 2026050);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (125, 'Fundamentals of Level', 2026045);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (126, 'Introduction to Town', 2026020);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (127, 'Principles of Bad', 2026028);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (128, 'Introduction to Stand', 2026041);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (129, 'Basics of Source', 2026031);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (130, 'Advanced Soldier', 2026015);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (131, 'Introduction to Majority', 2026008);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (132, 'Basics of Station', 2026014);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (133, 'Introduction to Hot', 2026034);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (134, 'Fundamentals of Apply', 2026041);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (135, 'Introduction to Responsibility', 2026035);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (136, 'Principles of Yourself', 2026035);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (137, 'Advanced This', 2026004);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (138, 'Advanced Eat', 2026021);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (139, 'Advanced Sit', 2026033);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (140, 'Principles of Scientist', 2026026);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (141, 'Introduction to Seven', 2026009);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (142, 'Fundamentals of Spend', 2026048);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (143, 'Advanced Cup', 2026010);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (144, 'Basics of Clear', 2026039);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (145, 'Basics of Make', 2026013);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (146, 'Principles of Today', 2026037);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (147, 'Principles of Pm', 2026046);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (148, 'Advanced Can', 2026048);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (149, 'Introduction to Thus', 2026022);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (150, 'Basics of Top', 2026008);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (151, 'Fundamentals of Wide', 2026006);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (152, 'Fundamentals of Red', 2026027);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (153, 'Advanced End', 2026043);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (154, 'Introduction to Movement', 2026014);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (155, 'Basics of Game', 2026013);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (156, 'Fundamentals of Community', 2026009);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (157, 'Fundamentals of Hot', 2026016);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (158, 'Introduction to Full', 2026044);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (159, 'Advanced According', 2026038);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (160, 'Basics of Leg', 2026046);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (161, 'Advanced Because', 2026026);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (162, 'Basics of Full', 2026007);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (163, 'Principles of Push', 2026023);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (164, 'Basics of Time', 2026006);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (165, 'Principles of Visit', 2026012);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (166, 'Basics of West', 2026013);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (167, 'Introduction to Itself', 2026026);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (168, 'Advanced Hear', 2026010);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (169, 'Advanced Tend', 2026025);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (170, 'Advanced Morning', 2026050);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (171, 'Introduction to Believe', 2026008);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (172, 'Basics of Big', 2026012);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (173, 'Introduction to Far', 2026004);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (174, 'Basics of Dog', 2026005);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (175, 'Advanced Detail', 2026047);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (176, 'Advanced Thousand', 2026024);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (177, 'Fundamentals of Take', 2026008);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (178, 'Fundamentals of Shoulder', 2026050);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (179, 'Introduction to Economic', 2026024);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (180, 'Introduction to Kind', 2026030);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (181, 'Advanced Task', 2026035);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (182, 'Principles of Four', 2026032);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (183, 'Principles of Defense', 2026003);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (184, 'Fundamentals of Majority', 2026023);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (185, 'Principles of Late', 2026037);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (186, 'Advanced Police', 2026031);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (187, 'Principles of Brother', 2026025);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (188, 'Basics of Attack', 2026020);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (189, 'Advanced Anything', 2026022);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (190, 'Advanced Republican', 2026024);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (191, 'Basics of And', 2026019);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (192, 'Introduction to Until', 2026018);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (193, 'Fundamentals of Network', 2026033);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (194, 'Fundamentals of Run', 2026039);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (195, 'Basics of Pretty', 2026023);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (196, 'Basics of Above', 2026024);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (197, 'Introduction to Audience', 2026047);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (198, 'Introduction to Agree', 2026010);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (199, 'Introduction to Bag', 2026049);
INSERT INTO Course (course_id, title, lecturer_id) VALUES (200, 'Principles of Win', 2026049);