INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Paper', 2026001);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Once', 2026002);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Ever', 2026003);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Role', 2026004);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Road', 2026005);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Floor', 2026006);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Member', 2026007);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Case', 2026008);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Name', 2026009);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Security', 2026010);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Report', 2026011);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced During', 2026012);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Executive', 2026013);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Education', 2026014);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Once', 2026015);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Behind', 2026016);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Energy', 2026017);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Ok', 2026018);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Effect', 2026019);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Million', 2026020);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Blood', 2026021);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Arm', 2026022);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Many', 2026023);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Capital', 2026024);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Building', 2026025);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Director', 2026026);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Free', 2026027);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Night', 2026028);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Lay', 2026029);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Get', 2026030);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Well', 2026031);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Table', 2026032);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Time', 2026033);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Different', 2026034);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Reach', 2026035);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Threat', 2026036);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Data', 2026037);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Certainly', 2026038);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of War', 2026039);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Arrive', 2026040);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Attention', 2026041);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of History', 2026042);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Treatment', 2026043);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Between', 2026044);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Month', 2026045);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Pass', 2026046);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Across', 2026047);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Here', 2026048);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Both', 2026049);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Pay', 2026050);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Son', 2026015);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Leave', 2026035);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Production', 2026048);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Why', 2026033);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Friend', 2026011);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Similar', 2026021);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of World', 2026024);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Message', 2026014);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Already', 2026006);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Million', 2026047);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Very', 2026015);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Focus', 2026043);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Data', 2026043);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Among', 2026030);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Statement', 2026020);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Activity', 2026043);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Happy', 2026019);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Sing', 2026039);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Camera', 2026028);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Tell', 2026015);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Drop', 2026003);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Fund', 2026009);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Guy', 2026005);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Play', 2026025);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Fund', 2026050);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Open', 2026037);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Magazine', 2026019);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of News', 2026028);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Involve', 2026045);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Pass', 2026039);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Itself', 2026008);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Eye', 2026047);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Late', 2026041);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Back', 2026010);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Little', 2026050);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Pretty', 2026033);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Worker', 2026003);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Staff', 2026019);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Full', 2026006);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Impact', 2026038);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Each', 2026044);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Gas', 2026029);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Nor', 2026033);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of By', 2026018);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Money', 2026049);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Best', 2026043);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Player', 2026019);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Range', 2026023);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Serve', 2026029);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of White', 2026031);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Establish', 2026003);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Pretty', 2026026);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Although', 2026016);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Suffer', 2026009);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Task', 2026012);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Might', 2026045);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Check', 2026028);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Summer', 2026016);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Like', 2026010);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Respond', 2026045);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Return', 2026028);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Upon', 2026012);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Whole', 2026044);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of My', 2026038);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Address', 2026005);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Society', 2026038);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Drug', 2026022);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Style', 2026026);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Yeah', 2026017);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Morning', 2026047);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Center', 2026038);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Big', 2026048);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Happy', 2026018);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Energy', 2026048);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Each', 2026014);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Who', 2026022);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Begin', 2026022);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Fill', 2026002);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Name', 2026024);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Common', 2026050);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Too', 2026013);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Resource', 2026036);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Process', 2026040);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of What', 2026025);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Officer', 2026013);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Increase', 2026050);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Paper', 2026047);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Base', 2026040);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Citizen', 2026017);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Social', 2026041);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Black', 2026044);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced People', 2026031);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Somebody', 2026048);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Guess', 2026021);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Meeting', 2026008);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Indeed', 2026012);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Their', 2026035);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Couple', 2026010);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Partner', 2026004);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Type', 2026029);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Cause', 2026013);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Guess', 2026020);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Building', 2026024);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Letter', 2026027);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Door', 2026008);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Raise', 2026039);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Test', 2026049);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Series', 2026023);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Ball', 2026011);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Stand', 2026032);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Or', 2026010);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Affect', 2026008);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Less', 2026031);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Sure', 2026020);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Win', 2026027);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Evidence', 2026011);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Social', 2026046);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Discussion', 2026009);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Hour', 2026026);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Reveal', 2026037);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Wish', 2026005);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Similar', 2026022);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Set', 2026020);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Race', 2026045);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Would', 2026034);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Structure', 2026034);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Mean', 2026018);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Worker', 2026041);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Them', 2026029);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of In', 2026024);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Wish', 2026027);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Board', 2026044);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Left', 2026049);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Certainly', 2026030);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Maintain', 2026033);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Month', 2026049);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Very', 2026005);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Game', 2026014);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Phone', 2026027);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Oil', 2026001);
INSERT INTO Course (title, lecturer_id) VALUES ('Introduction to Yeah', 2026042);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Behind', 2026034);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Discover', 2026039);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Meet', 2026040);
INSERT INTO Course (title, lecturer_id) VALUES ('Fundamentals of Heart', 2026009);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of In', 2026006);
INSERT INTO Course (title, lecturer_id) VALUES ('Principles of Become', 2026006);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Per', 2026041);
INSERT INTO Course (title, lecturer_id) VALUES ('Basics of Center', 2026007);
INSERT INTO Course (title, lecturer_id) VALUES ('Advanced Behind', 2026012);
